### ISSUE TITLE
Lua error using hearthbag with Litebag

### ISSUE THREAD

**Issue by Luellin** [keyboardturner/Hearthbag#1]
Hi i get this error while using /hb reset with Litebag, the version of hearthbag is 0.1.8 in retail , the version of litebag is 10.0.17, i used only heartbag, litebag, bugsack and bug grabber and obtain the same error.
 
1x Hearthbag/Hearthbag_Mainline.lua:1074: attempt to index a nil value
[string "@Hearthbag/Hearthbag_Mainline.lua"]:1074: in function `FrameLevelOrganiser'
[string "@Hearthbag/Hearthbag_Mainline.lua"]:3542: in function <Hearthbag/Hearthbag_Mainline.lua:3528>
[string "=[C]"]: ?

Locals:
(*temporary) = 600
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
hearthbag = Hearthbag {
 0 = <userdata>
 kyrian = HearthbagKyrian {
 }
 scrollbackFrame = ScrollBackFrame {
 }
 halloween = HearthbagHalloween {
 }
 CheckButton1Status_OnShow = <function> defined @Hearthbag/Hearthbag_Mainline.lua:785
 CheckButton1Up_OnClick = <function> defined @Hearthbag/Hearthbag_Mainline.lua:764
 size = 32
 hearthDestroyed = <function> defined @Hearthbag/Hearthbag_Mainline.lua:1189
 previewFrame = PreviewFrame {
 }
 love = HearthbagLove {
 }
 darkportal = HearthbagDarkportal {
 }
 CheckButton0Status_OnShow = <function> defined @Hearthbag/Hearthbag_Mainline.lua:690
 option0 = HearthbagOption0 {
 }
 previewFrameTex = PreviewFrameTex {
 }
 UpdateCheckCombat_OnClick = <function> defined @Hearthbag/Hearthbag_Mainline.lua:755
 checkboxbg0Tex = ScrollBackTex0 {
 }
 CheckButton2Up_OnClick = <function> defined @Hearthbag/Hearthbag_Mainline.lua:839
 CheckButton2Tooltip_OnEnter = <function> defined @Hearthbag/Hearthbag_Mainline.lua:863
 checkboxbg3Tex = ScrollBackTex1 {
 }
 checkboxbg1 = CheckBoxBG1 {
 }
 maxAmp = 4
 OnEvent = <function> defined @Hearthbag/Hearthbag_Mainline.lua:3528
 scrollbackButton = ScrollBackButton {
 }
 UpdateCheckInherit_OnClick = <function> defined @Hearthbag/Hearthbag_Mainline.lua:643
 rubySlippers = HearthbagRubySlippers {
 }
 frames = <table> {
 }
 smallbuttonup_ONMOUSEUP = <function> defined @Hearthbag/Hearthbag_Mainline.lua:612
 combatOptions = HearthCombat {
 }
 hearthBag_OnMouseUp = <function> defined @Hearthbag/Hearthbag_Mainline.lua:1165
 frameSelector = FrameSelector {
 }
 CheckButton0Tooltip_OnEnter = <function> defined @Hearthbag/Hearthbag_Mainline.lua:707
 diablo = HearthbagDiablo {
 }
 microMovementD = HearthArrowD {
 }
 checkboxbg2 = CheckBoxBG2 {
 }
 crimbo = HearthbagCrimbo {
 }
 broker = HearthbagBroker {
 }
 brewfest = HearthbagBrewfest {
 }
 CheckButton2Status_OnShow = <function> defined @Hearthbag/Hearthbag_Mainline.lua:854
 UpdatePositionLeft_OnClick = <function> defined @Hearthbag/Hearthbag_Mainline.lua:1019
 RandomSoundButton_Up = <function> defined @Hearthbag/Hearthbag_Mainline.lua:1119
 CheckButton3Status_OnShow = <function> defined @Hearthbag/Hearthbag_Mainline.lua:929
 scrollbackendButton = ScrollBackEndButton {
 }
 checkboxbg3 = CheckBoxBG3 {
 }
 CheckButton1Tooltip_OnLeave = <function> defined @Hearthbag/Hearthbag_Mainline.lua:810
 midsummer = HearthbagMidsummer {
 }
 smallbuttondown_ONMOUSEDOWN = <function> defined @Hearthbag/Hearthbag_Mainline.lua:608
 noble = HearthbagNoble {
 }
 centaur = HearthbagCentaur {
 }
 minAmp = 1
 inndaughter = HearthbagInndaughter {
 }
 CheckButton2Tooltip_OnLeave = <function> defined @Hearthbag/Hearthbag_Mainline.lua:879
 nudgeParent = NudgeParent {
 }
 UpdatePositionDown_OnClick = <function> defined @Hearthbag/Hearthbag_Mainline.lua:1038
 background = Texture {
 }
 inCombatOptions = HearthInCombat {
 }
 lunar = HearthbagLunar {
 }
 checkboxbg0 = CheckBoxBG0 {
 }
 CheckButton3Tooltip_OnEnter = <function> defined @Hearthbag/Hearthbag_Mainline.lua:938
 torghast = HearthbagTorghast {
 }
 microMovementL = HearthArrowL {
 }
 hearthCD = HearthCD {
 }
 buttonResetter = <function> defined @Hearthbag/Hearthbag_Mainline.lua:3213
 necrolord = HearthbagNecro {
 }
 CheckButton3Tooltip_OnLeave = <function> defined @Hearthbag/Hearthbag_Mainline.lua:954
 garrisonHearth = GarrisonHearth {
 }
 hearthBag_OnMouseDown = <function> defined @Hearthbag/Hearthbag_Mainline.lua:1126
 oribos = HearthbagOribos {
 }
 itemHolderFrameTex = ItemHolderFrameTex {
 }
 itemHolderFrame = ItemHolderFrame {
 }
 checkboxbg1Tex = ScrollBackTex1 {

**Comment by keyboardturner** [comment]
Next update should fix this issue, thanks for the report. LiteBag is a nice addon, haven't used it in a while since Blizz effectively replaced it for me. Seems it got a rework since i last used it and removed the frame I parented to.
